config/routes.rb
Infotree::Application.routes.draw do
  resources :unit_of_measure_conversions do
    collection do
      post 'edit_individual'
      put 'update_individual'
    end
  end 

  match '/sforms/GMC002' => 'unit_of_measure_conversions#index'

  resources :unit_of_measures do
    collection do
      post 'edit_individual'
      put 'update_individual'
    end
  end 


  match '/sforms/GMC001' => 'unit_of_measures#index'

  get "welcome/index"

  get "sforms/MNT001"

  get "sforms/MNT002"

  get "sforms/BOM001"

  get "sforms/ACR001"

  get "sforms/APR001"

  get "sforms/CRM001"

  get "sforms/MNT"

  get "sforms/BOM"

  get "sforms/ACR"

  get "sforms/APR"

  get "sforms/ABC400"

  get "sforms/ACR400"

  get "sforms/APA400"

  get "sforms/BOM400"

  get "sforms/BOM002"

  get "sforms/CAP400"

  get "sforms/COS400"

  get "sforms/DEC400"

  get "sforms/EMT400"

  get "sforms/FAS400"

  get "sforms/FOR400"

  get "sforms/FGL400"

  get "sforms/MNT400"

  get "sforms/MPS400"

  get "sforms/MRP400"

  get "sforms/OEI400"

  get "sforms/INV400"

  get "sforms/SFW400"

  get "sforms/PUR400"

  get "sforms/REW400"

  get "sforms/GMC400"

  get "sforms/QAS400"

  

  resources :pages









  root :to => 'welcome#index'


end

app/models/unit_of_measure.rb
class UnitOfMeasure < ActiveRecord::Base

validates :uom, :uom_desc, :presence => true
validates :uom, :uniqueness => true

before_validation :uppercase_uom

def uppercase_uom
    self.uom.upcase!
end


validates :uom, :length => {
    :maximum => 4, 
    :message => 'must be less than 4 characters long.'
  }
validates :uom_desc, :length => {
    :maximum => 15, 
    :message => 'must be less than 15 characters long.'
  }
validates :comments, :length => {
    :maximum => 80, 
    :message => 'must be less than 80 characters long.'
  }

  has_many :primary_uomcs, :class_name => "UnitOfMeasureConversion", :foreign_key => "primary_uom_id", :dependent => :restrict
  has_many :secondary_uomcs, :class_name => "UnitOfMeasureConversion", :foreign_key => "secondary_uom_id", :dependent => :restrict


end

app/controllers/unit_of_measures_controller.rb
class UnitOfMeasuresController < ApplicationController
  # GET /unit_of_measures
  # GET /unit_of_measures.json
  def index
    @unit_of_measures = UnitOfMeasure.order(:uom).page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unit_of_measures }
    end
  end

  # GET /unit_of_measures/1
  # GET /unit_of_measures/1.json
  def show
    @unit_of_measure = UnitOfMeasure.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit_of_measure }
    end
  end

  # GET /unit_of_measures/new
  # GET /unit_of_measures/new.json
  def new
    @unit_of_measure = UnitOfMeasure.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit_of_measure }
    end
  end

  # GET /unit_of_measures/1/edit
  def edit
    @unit_of_measure = UnitOfMeasure.find(params[:id])
  end

  # POST /unit_of_measures
  # POST /unit_of_measures.json
  def create
    @unit_of_measure = UnitOfMeasure.new(params[:unit_of_measure])

    respond_to do |format|
      if @unit_of_measure.save
        format.html { redirect_to @unit_of_measure, notice: 'Unit of measure was successfully created.' }
        format.json { render json: @unit_of_measure, status: :created, location: @unit_of_measure }
      else
        format.html { render action: "new" }
        format.json { render json: @unit_of_measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unit_of_measures/1
  # PUT /unit_of_measures/1.json
  def update
    @unit_of_measure = UnitOfMeasure.find(params[:id])

    respond_to do |format|
      if @unit_of_measure.update_attributes(params[:unit_of_measure])
        format.html { redirect_to @unit_of_measure, notice: 'Unit of measure was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit_of_measure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_of_measures/1
  # DELETE /unit_of_measures/1.json
  def destroy
    @unit_of_measure = UnitOfMeasure.find(params[:id])
    @unit_of_measure.destroy

    respond_to do |format|
      format.html { redirect_to unit_of_measures_url }
      format.json { head :no_content }
    end
  end

  def edit_individual
    @unit_of_measures = UnitOfMeasure.find(params[:unit_of_measure_ids])
    if params[:delete]
      @unit_of_measures.each do |uom|
        UnitOfMeasure.destroy(uom.id)
      end
      redirect_to unit_of_measures_url(:page => params[:cur_page])
    elsif params[:details]
      render :template => 'unit_of_measures/show_details.html.erb'
    else
      render :template => 'unit_of_measures/edit_individual.html.erb'
    end
  end

  def update_individual
    UnitOfMeasure.update(params[:uoms].keys, params[:uoms].values)
    redirect_to unit_of_measures_url(:page => params[:cur_page])
  end

end

app/helpers/unit_of_measures_helper.rb
module UnitOfMeasuresHelper
end

app/views/unit_of_measures/_form.html.erb
<%= form_for(@unit_of_measure) do |f| %>
  <% if @unit_of_measure.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit_of_measure.errors.count, "error") %> prohibited this unit_of_measure from being saved:</h2>

      <ul>
      <% @unit_of_measure.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uom %><br />
    <%= f.text_field :uom, :size => 10 %>
  </div>
  <div class="field">
    <%= f.label :uom_desc %><br />
    <%= f.text_field :uom_desc, :size => 30 %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, :rows => 5, :cols => 25 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unit_of_measures/edit.html.erb
<h1>Editing Unit Of Measure</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit_of_measure %> |
<%= link_to 'Back', unit_of_measures_path %>

app/views/unit_of_measures/edit_individual.html.erb
<h1>Editing Units Of Measure</h1>

  <%= form_tag update_individual_unit_of_measures_path, :method => :put do %>

<table>
  <tr>
    <th>Code</th>
    <th>Description</th>
    <th>Comments</th>
  </tr>

  
    <% @unit_of_measures.each do |uom| %>

    <%= hidden_field_tag 'cur_page', params[:cur_page] %>

      <%= fields_for "uoms[]", uom do |f| %>

     <tr>
    <td><%= f.text_field :uom, :size => 10 %></td>

    <td><%= f.text_field :uom_desc, :size => 30 %></td>

    <td><%= f.text_area :comments, :rows => 5, :cols => 25 %><td>


   </tr> 

      <% end %>
  
    <% end %>  



</table>

  <p> <%= submit_tag "Submit" %></p>

  <% end %>

<%= link_to 'Back', unit_of_measures_path(:page => params[:cur_page]) %>

app/views/unit_of_measures/index.html.erb
<h1>Listing Units Of Measure</h1>

<%= paginate @unit_of_measures %>

</br> 

<% if @unit_of_measures.empty? %>
  <% msg = "There are no Units Of Measure created." %>
  <%= msg %>
<% else %>

<%= form_tag edit_individual_unit_of_measures_path do %>

<table id="rindex">
  <tr>
    <th><%= check_box_tag('check_all', '1', false, :onClick => "myCheckAll($(this).prop('checked')); ") %></th>
    <th>Uom</th>
    <th>Uom desc</th>
    <th>Comments</th>
  </tr>

<% @unit_of_measures.each_with_index do |unit_of_measure, i| %>
  <% if i.even? %>
      <% w='even' %>
      <tr class="alt">
    <% else %>
      <% w='odd' %>
      <tr>
    <% end %>
    <%= hidden_field_tag 'cur_page', params[:page] %>
    <td><%= check_box_tag "unit_of_measure_ids[]", unit_of_measure.id %></td>
    <td><%= unit_of_measure.uom %></td>
    <td><%= unit_of_measure.uom_desc %></td>
    <td><%= unit_of_measure.comments %></td>
  </tr>
<% end %>
</table>

<p><%= submit_tag "Edit Checked", :name => 'edit' %>
   <%= submit_tag "Show Checked", :name => 'details' %>
   <%= submit_tag "Delete Checked", :name => 'delete', :confirm => "Are you sure you want to delete these?" %>
</p>


<% end %>

<% end %>
<br />

<%= link_to 'New Unit of measure', new_unit_of_measure_path %>

app/views/unit_of_measures/new.html.erb
<h1>New Unit Of Measure</h1>

<%= render 'form' %>

<%= link_to 'Back', unit_of_measures_path %>

app/views/unit_of_measures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Uom:</b>
  <%= @unit_of_measure.uom %>
</p>

<p>
  <b>Uom desc:</b>
  <%= @unit_of_measure.uom_desc %>
</p>

<p>
  <b>Comments:</b>
  <%= @unit_of_measure.comments %>
</p>


<%= link_to 'Edit', edit_unit_of_measure_path(@unit_of_measure) %> |
<%= link_to 'Back', unit_of_measures_path %>

app/views/unit_of_measures/show_details.html.erb
<h1>Unit Of Measure Details</h1>

<table id="rindex">
  <tr>
    
    <th>Code</th>
    <th>Description</th>
    <th>Comments</th>
  </tr>

<% @unit_of_measures.each_with_index do |uom, i| %>
  <% if i.even? %>
      <% w='even' %>
      <tr class="alt">
    <% else %>
      <% w='odd' %>
      <tr>
    <% end %>
    
    <td><%= uom.uom %></td>
    <td><%= uom.uom_desc %></td>
    <td><%= uom.comments %></td>
    
     
  </tr>
<% end %>
</table>




<%= link_to 'Back', unit_of_measures_path(:page => params[:cur_page]) %>



