config/routes.rb
Infotree::Application.routes.draw do
  resources :unit_of_measure_conversions do
    collection do
      post 'edit_individual'
      put 'update_individual'
    end
  end 

  match '/sforms/GMC002' => 'unit_of_measure_conversions#index'

  resources :unit_of_measures do
    collection do
      post 'edit_individual'
      put 'update_individual'
    end
  end 


  match '/sforms/GMC001' => 'unit_of_measures#index'

  get "welcome/index"

  get "sforms/MNT001"

  get "sforms/MNT002"

  get "sforms/BOM001"

  get "sforms/ACR001"

  get "sforms/APR001"

  get "sforms/CRM001"

  get "sforms/MNT"

  get "sforms/BOM"

  get "sforms/ACR"

  get "sforms/APR"

  get "sforms/ABC400"

  get "sforms/ACR400"

  get "sforms/APA400"

  get "sforms/BOM400"

  get "sforms/BOM002"

  get "sforms/CAP400"

  get "sforms/COS400"

  get "sforms/DEC400"

  get "sforms/EMT400"

  get "sforms/FAS400"

  get "sforms/FOR400"

  get "sforms/FGL400"

  get "sforms/MNT400"

  get "sforms/MPS400"

  get "sforms/MRP400"

  get "sforms/OEI400"

  get "sforms/INV400"

  get "sforms/SFW400"

  get "sforms/PUR400"

  get "sforms/REW400"

  get "sforms/GMC400"

  get "sforms/QAS400"

  

  resources :pages









  root :to => 'welcome#index'


end

app/models/unit_of_measure_conversion.rb
class UnitOfMeasureConversion < ActiveRecord::Base

validates :conversion_factor, :primary_uom_id, :secondary_uom_id, :presence => true

validates :item_no, :length => {
    :maximum => 15, 
    :message => 'must be less than 15 characters long.'
  }
validates :comments, :length => {
    :maximum => 80, 
    :message => 'must be less than 80 characters long.'
  }

  belongs_to :puoms, :class_name => "UnitOfMeasure", :foreign_key => "primary_uom_id"
  belongs_to :suoms, :class_name => "UnitOfMeasure", :foreign_key => "secondary_uom_id"

end

app/controllers/unit_of_measure_conversions_controller.rb
class UnitOfMeasureConversionsController < ApplicationController
  # GET /unit_of_measure_conversions
  # GET /unit_of_measure_conversions.json
  def index
    @unit_of_measure_conversions = UnitOfMeasureConversion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unit_of_measure_conversions }
    end
  end

  # GET /unit_of_measure_conversions/1
  # GET /unit_of_measure_conversions/1.json
  def show
    @unit_of_measure_conversion = UnitOfMeasureConversion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unit_of_measure_conversion }
    end
  end

  # GET /unit_of_measure_conversions/new
  # GET /unit_of_measure_conversions/new.json
  def new
    @unit_of_measure_conversion = UnitOfMeasureConversion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unit_of_measure_conversion }
    end
  end

  # GET /unit_of_measure_conversions/1/edit
  def edit
    @unit_of_measure_conversion = UnitOfMeasureConversion.find(params[:id])
  end

  # POST /unit_of_measure_conversions
  # POST /unit_of_measure_conversions.json
  def create
    @unit_of_measure_conversion = UnitOfMeasureConversion.new(params[:unit_of_measure_conversion])

    respond_to do |format|
      if @unit_of_measure_conversion.save
        format.html { redirect_to @unit_of_measure_conversion, notice: 'Unit of measure conversion was successfully created.' }
        format.json { render json: @unit_of_measure_conversion, status: :created, location: @unit_of_measure_conversion }
      else
        format.html { render action: "new" }
        format.json { render json: @unit_of_measure_conversion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /unit_of_measure_conversions/1
  # PUT /unit_of_measure_conversions/1.json
  def update
    @unit_of_measure_conversion = UnitOfMeasureConversion.find(params[:id])

    respond_to do |format|
      if @unit_of_measure_conversion.update_attributes(params[:unit_of_measure_conversion])
        format.html { redirect_to @unit_of_measure_conversion, notice: 'Unit of measure conversion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unit_of_measure_conversion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_of_measure_conversions/1
  # DELETE /unit_of_measure_conversions/1.json
  def destroy
    @unit_of_measure_conversion = UnitOfMeasureConversion.find(params[:id])
    @unit_of_measure_conversion.destroy

    respond_to do |format|
      format.html { redirect_to unit_of_measure_conversions_url }
      format.json { head :no_content }
    end
  end

  def edit_individual
    @unit_of_measure_conversions = UnitOfMeasureConversion.find(params[:unit_of_measure_conversion_ids])
    if params[:delete]
      @unit_of_measure_conversions.each do |uom|
        UnitOfMeasureConversion.destroy(uom.id)
      end
      redirect_to unit_of_measure_conversions_url
    elsif params[:details]
      render :template => 'unit_of_measure_conversions/show_details.html.erb'
    else
      render :template => 'unit_of_measure_conversions/edit_individual.html.erb'
    end
  end

  def update_individual
    UnitOfMeasureConversion.update(params[:uom_convs].keys, params[:uom_convs].values)
    redirect_to unit_of_measure_conversions_url
  end

end

app/helpers/unit_of_measure_conversions_helper.rb
module UnitOfMeasureConversionsHelper
end

app/views/unit_of_measure_conversions/_form.html.erb
<%= form_for(@unit_of_measure_conversion) do |f| %>
  <% if @unit_of_measure_conversion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit_of_measure_conversion.errors.count, "error") %> prohibited this unit_of_measure_conversion from being saved:</h2>

      <ul>
      <% @unit_of_measure_conversion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :conversion_factor %><br />
    <%= f.text_field :conversion_factor, :size => 10 %>
  </div>
  <div class="field">
    <%= f.label :primary_uom %><br />
    <%= f.collection_select :primary_uom_id, UnitOfMeasure.all(:order => "uom_desc"), :id, :uom_desc %>
  </div>
  <div class="field">
    <%= f.label :secondary_uom %><br />
    <%= f.collection_select :secondary_uom_id, UnitOfMeasure.all(:order => "uom_desc"), :id, :uom_desc %>
  </div>
  <div class="field">
    <%= f.label :item_no %><br />
    <%= f.text_field :item_no, :size => 25 %>
  </div>
  <div class="field">
    <%= f.label :from_effective_date %><br />
    <%= f.date_select :from_effective_date %>
  </div>
  <div class="field">
    <%= f.label :to_effective_date %><br />
    <%= f.date_select :to_effective_date %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments, :rows => 5, :cols => 25 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/unit_of_measure_conversions/edit.html.erb
<h1>Editing unit_of_measure_conversion</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit_of_measure_conversion %> |
<%= link_to 'Back', unit_of_measure_conversions_path %>

app/views/unit_of_measure_conversions/edit_individual.html.erb
<h1>Editing Unit Of Measure Conversions</h1>

  <%= form_tag update_individual_unit_of_measure_conversions_path, :method => :put do %>

<table>
 
    <% @unit_of_measure_conversions.each do |uomc| %>

      <%= fields_for "uom_convs[]", uomc do |f| %>

  <tr>
    <th>Conversion Factor</th>
    <th>Primary Uom</th>
    <th>Secondary Uom</th>
  </tr>

     <tr>
    <td><%= f.text_field :conversion_factor, :size => 10 %></td>

    <td><%= f.collection_select :primary_uom_id, UnitOfMeasure.all(:order => "uom_desc"), :id, :uom_desc %></td>
  
    <td><%= f.collection_select :secondary_uom_id, UnitOfMeasure.all(:order => "uom_desc"), :id, :uom_desc %></td>
    
    </tr>

    <tr>
    <th>Item No.</th>
    <th>From Effective Date</th>
    <th>To Effective Date</th>
  </tr>


    <tr>

    <td><%= f.text_field :item_no, :size => 25 %></td>

    <td><%= f.date_select :from_effective_date %></td>

    <td><%= f.date_select :to_effective_date %></td>

    </tr>

  <tr>
    <th>Comments</th>
  </tr>

    <tr>

    <td><%= f.text_area :comments, :rows => 5, :cols => 25 %><td>

    </tr>

   </tr> 

      <% end %>
  
    <% end %>  



</table>

  <p> <%= submit_tag "Submit" %></p>

  <% end %>

<%= link_to 'Back', unit_of_measure_conversions_path %>

app/views/unit_of_measure_conversions/index.html.erb
<h1>Listing Unit Of Measure Conversions</h1>

<% if @unit_of_measure_conversions.empty? %>
  <%= "There are no Unit Of Measure Conversions created." %>
  
<% else %>

<%= form_tag edit_individual_unit_of_measure_conversions_path do %>

<table id="rindex">
  <tr>
    <th><%= check_box_tag('check_all', '1', false, :onClick => "myCheckAll($(this).prop('checked')); ") %></th>
    <th>Conversion Factor</th>
    <th>Primary Uom</th>
    <th>Secondary Uom</th>
    <th>Item No.</th>
    <th>From Effective Date</th>
    <th>To Effective Date</th>
    <th>Comments</th>
  </tr>

<% @unit_of_measure_conversions.each_with_index do |uomc, i| %>
  <% if i.even? %>
      <% w='even' %>
      <tr class="alt">
    <% else %>
      <% w='odd' %>
      <tr>
    <% end %>
    <td><%= check_box_tag "unit_of_measure_conversion_ids[]", uomc.id %></td>
    <td><%= uomc.conversion_factor %></td>
    <td><%= uomc.puoms.uom %></td>
    <td><%= uomc.suoms.uom %></td>
    <td><%= uomc.item_no %></td>
    <td><%= uomc.from_effective_date %></td>
    <td><%= uomc.to_effective_date %></td>
    <td><%= uomc.comments %></td>
  </tr>
<% end %>
</table>

<p><%= submit_tag "Edit Checked", :name => 'edit' %>
   <%= submit_tag "Show Checked", :name => 'details' %>
   <%= submit_tag "Delete Checked", :name => 'delete', :confirm => "Are you sure you want to delete these?" %>
</p>


<% end %>

<% end %>

<br />

<%= link_to 'New Unit of measure conversion', new_unit_of_measure_conversion_path %>

app/views/unit_of_measure_conversions/new.html.erb
<h1>New Unit Of Measure Conversion</h1>

<%= render 'form' %>

<%= link_to 'Back', unit_of_measure_conversions_path %>

app/views/unit_of_measure_conversions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Conversion factor:</b>
  <%= @unit_of_measure_conversion.conversion_factor %>
</p>

<p>
  <b>Primary uom:</b>
  <%= @unit_of_measure_conversion.puoms.uom_desc %>
</p>

<p>
  <b>Secondary uom id:</b>
  <%= @unit_of_measure_conversion.suoms.uom_desc %>
</p>

<p>
  <b>Item no:</b>
  <%= @unit_of_measure_conversion.item_no %>
</p>

<p>
  <b>From effective date:</b>
  <%= @unit_of_measure_conversion.from_effective_date %>
</p>

<p>
  <b>To effective date:</b>
  <%= @unit_of_measure_conversion.to_effective_date %>
</p>

<p>
  <b>Comments:</b>
  <%= @unit_of_measure_conversion.comments %>
</p>


<%= link_to 'Edit', edit_unit_of_measure_conversion_path(@unit_of_measure_conversion) %> |
<%= link_to 'Back', unit_of_measure_conversions_path %>

app/views/unit_of_measure_conversions/show_details.html.erb
<h1>Unit Of Measure Conversion Details</h1>

<table id="rindex">
  <tr>
    
    <th>Conversion Factor</th>
    <th>Primary Uom</th>
    <th>Secondary Uom</th>
    <th>Item No.</th>
    <th>From Effective Date</th>
    <th>To Effective Date</th>
    <th>Comments</th>
  </tr>

<% @unit_of_measure_conversions.each_with_index do |uomc, i| %>
  <% if i.even? %>
      <% w='even' %>
      <tr class="alt">
    <% else %>
      <% w='odd' %>
      <tr>
    <% end %>
    
    <td><%= uomc.conversion_factor %></td>
    <td><%= uomc.puoms.uom_desc %></td>
    <td><%= uomc.suoms.uom_desc %></td>
    <td><%= uomc.item_no %></td>
    <td><%= uomc.from_effective_date %></td>
    <td><%= uomc.to_effective_date %></td>
    <td><%= uomc.comments %></td>
    
     
  </tr>
<% end %>
</table>




<%= link_to 'Back', unit_of_measure_conversions_path %>



