config/routes.rb
Infotree::Application.routes.draw do
  resources :unit_of_measure_conversions do
    collection do
      post 'edit_individual'
      put 'update_individual'
    end
  end 

  match '/sforms/GMC002' => 'unit_of_measure_conversions#index'

  resources :unit_of_measures do
    collection do
      post 'edit_individual'
      put 'update_individual'
    end
  end 


  match '/sforms/GMC001' => 'unit_of_measures#index'

  get "welcome/index"

  get "sforms/MNT001"

  get "sforms/MNT002"

  get "sforms/BOM001"

  get "sforms/ACR001"

  get "sforms/APR001"

  get "sforms/CRM001"

  get "sforms/MNT"

  get "sforms/BOM"

  get "sforms/ACR"

  get "sforms/APR"

  get "sforms/ABC400"

  get "sforms/ACR400"

  get "sforms/APA400"

  get "sforms/BOM400"

  get "sforms/BOM002"

  get "sforms/CAP400"

  get "sforms/COS400"

  get "sforms/DEC400"

  get "sforms/EMT400"

  get "sforms/FAS400"

  get "sforms/FOR400"

  get "sforms/FGL400"

  get "sforms/MNT400"

  get "sforms/MPS400"

  get "sforms/MRP400"

  get "sforms/OEI400"

  get "sforms/INV400"

  get "sforms/SFW400"

  get "sforms/PUR400"

  get "sforms/REW400"

  get "sforms/GMC400"

  get "sforms/QAS400"

  

  resources :pages









  root :to => 'welcome#index'


end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.collection_select :parent_id, Page.all(:order => "name"), :id, :name, :include_blank => true %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/_page.html.erb
<ul>
  <% apages = Page.where(:parent_id => nil) %>
  <% apages.each do |apage| %>
    <% url = root_path + "welcome/index" %>
    <% idname = "Parent" + apage.id.to_s %>
    <li id=<%= idname %> class="h" href=<%= url %>><a href=<%= url %> ><%= apage.name %></a>
      <ul>
        <% @parent = apage.id %>
        <%= render :partial => "pages/subpage", :object => @parent %> 
      </ul>
    </li>
  <% end %>
</ul>
          

app/views/pages/_rsubpage.html.erb
<ul>
<% fpages = Page.all %>
            <% fpages.each do |spages| %>
              
                
		
                  <% idname = spages.id.to_s %>
                  <li id=<%= idname %> class="r"><a><%= spages.content %></a></li>
                  
             
              
            <% end %>
</ul>

app/views/pages/_subpage.html.erb

<% fpages = Page.where(:parent_id => subpage) %>
            <% fpages.each do |spages| %>
              
                <% level = Page.where(:parent_id => spages.id).count %>
		<% url = root_path + "sforms/" + spages.name %>
                <% if level == 0 %>
                  <% idname = "Child" + spages.id.to_s %>
                  <% titlename = spages.content %>
                  <li id=<%= idname %> class="h" href=<%= url %>><a  href=<%= url %>><%= spages.name %></a></li>
                  
                <% else %>
                  <% idname = "Parent" + spages.id.to_s %>
                  
                  <li id=<%= idname %> class="h" href=<%= url %>><a  href=<%= url %>><%= spages.name %></a>
                  <ul>
                  <%= render :partial => "pages/subpage", :object => spages.id %>
                  </ul>
                  </li>
                <% end %>
              
            <% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<%= paginate @pages %>

<table>
  <tr>
    <th>Id</th>
    <th>Parent</th>
    <th>Name</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.id %></td>
    <td><%= page.parent_id %></td>
    <td><%= page.name %></td>
    <td><%= page.content %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />



<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Parent:</b>
  <%= @page.parent_id %>
</p>

<p>
  <b>Name:</b>
  <%= @page.name %>
</p>

<p>
  <b>Content:</b>
  <%= @page.content %>
</p>


<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>